[package]
name = "hypospray_extensions"
version = "0.1.0"
authors = ["Jony <jonysy@users.noreply.github.com>"]
license = "MIT/Apache-2.0"

[lib]
plugin = true

[dependencies]
aster = "0.36.0"
quote = "0.3"